### ISSUE TITLE
在项目中用到 jquery 的插件 summernote, 多语言要怎么引用

### ISSUE THREAD

**Issue by alvin2ye** [spmjs/spm#1138]
![image](http://agi-public3.qiniudn.com/20150109175633/1.png)

package.json
```
{
  "name": "jquery.summernote",
  "version": "0.1.0",
  "description": "...",
  "keywords": [],
  "homepage": "",
  "author": "...",
  "repository": {
    "type": "git",
    "url": ""
  },
  "bugs": {
    "url": ""
  },
  "licenses": "MIT",
  "spm": {
    "main": "jquery.summernote.js",
    "output": ["lang/*.js"],
    "dependencies": {
    	"jquery": "2.1.1",
      "smartadmin-bootstrap": "0.0.1"
    },
    "devDependencies": {
      "expect.js": "0.3.1"
    }
  }
}

```

在使用中  show.js
```
var $ = require("jquery");
require("jquery.summernote")($);
require("jquery.summernote.zh")($);
```

seajs_config.js
```
seajs.config({
  base:  seajs.production ? "/static/dist" : "/static/sea_modules",
  alias: {
    "jquery" : "jquery/2.1.1/jquery",
    "jquery-ui" : "jquery-ui/1.11.1/jquery-ui",
    "jquery.summernote": "jquery.summernote/0.1.0/jquery.summernote",
    "jquery.summernote.zh": "jquery.summernote/0.1.0/lang/summernote-zh-CN"
  }
});

```

我部知道怎么引用插件的翻译文件比较好:
- 直接这样会抛 jquery.summernote.zh 包找不到
-  一样 require 我还要吧jquery.summernote.zh 改为一个 spm 包 太麻烦了.
- 把jquery.summernote.zh的内容负责到 jquery.summernote 里, 这样对维护不好.

难道是我误用了吗?

**Comment by afc163** [comment]
构建后的 jquery.summernote/0.1.0/lang/summernote-zh-CN.js 文件的 ID 是啥？

**Comment by afc163** [comment]
好像没有构建过程。

那 `jquery.summernote/0.1.0/lang/summernote-zh-CN.js` 文件的内容是啥？

**Comment by alvin2ye** [comment]
"jquery.summernote/0.1.0/lang/summernote-zh-CN"

**Comment by alvin2ye** [comment]
我简化后, 原文是
```
(function ($) {
  $.extend($.summernote.lang, {
    'zh-CN': {
      table: {
        table: '表格'
      }
    }
  });
})(jQuery);
```

我手工修改为
```

//@add
module.exports = function(jQuery) {
//@add
(function( factory ) {
if ( typeof define === "function" && define.amd ) {

// AMD. Register as an anonymous module.
define([ "jquery" ], factory );
} else {

// Browser globals
factory( jQuery );
}
}(function( $ ) {
 
  // =================   Jquery Plugin Code Start  ==================


(function ($) {
  $.extend($.summernote.lang, {
    'zh-CN': {
      table: {
        table: '表格'
      }
    }
  });
})(jQuery);


  // =================   Jquery Plugin Code End  ==================
}));

//@add
};
//@add

```

build 后
```
define("jquery.summernote/0.1.0/lang/summernote-zh-CN-debug", [], function(require, exports, module){

//@add
module.exports = function(jQuery) {
//@add
(function( factory ) {
if ( typeof define === "function" && define.amd ) {

// AMD. Register as an anonymous module.
define([ "jquery" ], factory );
} else {

// Browser globals
factory( jQuery );
}
}(function( $ ) {

  // =================   Jquery Plugin Code Start  ==================


(function ($) {
  $.extend($.summernote.lang, {
    'zh-CN': {
      table: {
        table: '表格'
      }
    }
  });
})(jQuery);


  // =================   Jquery Plugin Code End  ==================
}));

//@add
};
//@add


});

```

**Comment by afc163** [comment]
> 直接这样会抛 jquery.summernote.zh 包找不到

按上面的信息，感觉这里不应该出现这个问题。要是能搞个 live demo 访问下就好了。

**Comment by alvin2ye** [comment]
我可能没说清楚是build得时候错误

```
cd /public/static && spm build --include all --ignore "jquery,jquery-ui" -O ./dist

```
```
jquery.summernote.zh is not in dependencies but required by app/contacts/show.js:
Error: jquery.summernote.zh is not in dependencies but required by app/contacts/show.js
    at getDepFile (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:212:11)
    at /usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:170:17
    at Array.forEach (native)
    at lookupDeps (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:154:4)
    at SubClass.<anonymous> (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:119:7)
    at Array.forEach (native)
    at SubClass.Class.create._parseFiles (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:117:34)
    at SubClass.Class.create._parse (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:98:10)
    at SubClass.Class.create.initialize (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:45:10)
    at new SubClass (/usr/local/lib/node_modules/spm/node_modules/father/node_modules/arale/lib/class.js:53:23):
```

**Comment by afc163** [comment]
`show.js` 有构建过程就好办。可以这样：

```js
var $ = require("jquery");
require("jquery.summernote")($);
require("jquery.summernote/lang/summernote-zh-CN")($);
```

这是直接依赖包内其他文件的方式，在 spm@3.2.0 时加入。https://github.com/spmjs/spm/releases/tag/3.2.0

**Comment by alvin2ye** [comment]
@afc163 确实可以, 谢谢了. 

发现在 @sorrycc 的书里有详细解释, 第一次看漏了.

http://sorrycc.gitbooks.io/spm-handbook/content/develop-package/include-package-files.html
