### ISSUE TITLE
placeholders.js is not in dependencies but required by ...

### ISSUE THREAD

**Issue by crossjs** [spmjs/spm#1154]
配置文件：

```json
"dependencies": {
  "placeholders.js": "3.0.2"
}
```

spm build 时出现：

```
Error: placeholders.js is not in dependencies but required by mod\form\index.js
    at getDepFile (C:\Program Files\nodejs\node_modules\spm\node_modules\father\lib\package.js:212:11)
    at C:\Program Files\nodejs\node_modules\spm\node_modules\father\lib\package.js:170:17
    at Array.forEach (native)
    at lookupDeps (C:\Program Files\nodejs\node_modules\spm\node_modules\father\lib\package.js:154:4)
    at C:\Program Files\nodejs\node_modules\spm\node_modules\father\lib\package.js:181:5
    at Array.forEach (native)
    at lookupDeps (C:\Program Files\nodejs\node_modules\spm\node_modules\father\lib\package.js:154:4)
    at SubClass.<anonymous> (C:\Program Files\nodejs\node_modules\spm\node_modules\father\lib\package.js:119:7)
    at Array.forEach (native)
    at SubClass.Class.create._parseFiles (C:\Program Files\nodejs\node_modules\spm\node_modules\father\lib\package.js:117:34):
```

怀疑是不是模块名带 `.js` ？

**Comment by crossjs** [comment]
可能搞错，先研究下

**Comment by sorrycc** [comment]
https://github.com/spmjs/Placeholders.js/blob/master/package.json#L2
name 里有大写， @afc163

**Comment by crossjs** [comment]
果然，是因为 name 里有大写 …… 打了 log 才发现。

**Comment by popomore** [comment]
如果 name 大写应该发的包名也是大写吧，是不是 publish 的 bug

**Comment by sorrycc** [comment]
name 不允许大写的，publish 时未做校验。

**Comment by popomore** [comment]
哦，那就对了

**Comment by popomore** [comment]
记作一个bug

**Comment by afc163** [comment]
publish 时会把 name 一律转成小写的，build 的时候也转换一下吧。

**Comment by sorrycc** [comment]
name 不符合规范直接提示出错会不会更好?  要转换的话可能调试和构建的时候都要做。

**Comment by popomore** [comment]
感觉提示更好

**Comment by afc163** [comment]
也行，主要是有些没发到 npm 的著名库里面的 package.json 就是有大写。比如这个 placeholders.js 。

我重新发了下这个 placeholders.js 的包，@crossjs `spm install -f` 更新下就好。
