### ISSUE TITLE
spm build 错误, 这种错误要怎么调, 错误消息没说哪个包 ~~

### ISSUE THREAD

**Issue by alvin2ye** [spmjs/spm#1160]
```
      spm build --include all --ignore "jquery,jquery-ui" -O ./dist

          start: build wzhw@0.0.0
      arguments: cwd = $CWD
      arguments: dest = $CWD/dist
      arguments: O = null
      arguments: zip = false
      arguments: force = false
      arguments: withDeps = false
      arguments: install = true
      arguments: ignore = ["jquery","jquery-ui"]
      arguments: skip = [""]
      arguments: idleading = {{name}}/{{version}}
      arguments: include = all
      arguments: global = {}
      arguments: uglify = {"output":{"ascii_only":true}}
      arguments: cssmin = {}
      arguments: entry = []
      arguments: registry = http://spmjs.io
        install: expect.js@0.3.1
          found: expect.js@0.3.1
        install: seajs@2.3.0
          found: seajs@2.3.0
        install: seajs-wrap@1.0.2
          found: seajs-wrap@1.0.2
        install: jquery@2.1.1
          found: jquery@2.1.1
        install: jquery-ui@1.11.1
          found: jquery-ui@1.11.1
        install: jquery.jarvismenu@0.0.1
          found: jquery.jarvismenu@0.0.1
        install: smartadmin-bootstrap@*
          found: smartadmin-bootstrap@*
        install: jqgrid@4.6.0
          found: jqgrid@4.6.0
        install: moment@2.9.0
          found: moment@2.9.0
        install: arale-class@1.2.0
          found: arale-class@1.2.0
        install: jquery.summernote@0.1.0
          found: jquery.summernote@0.1.0
        install: xs.art-template@3.0.0
          found: xs.art-template@3.0.0
        install: at2@0.5.2
          found: at2@0.5.2
        install: seajs-text@1.1.0
          found: seajs-text@1.1.0
        install: easy-pagination2@1.0.1
          found: easy-pagination2@1.0.1
        install: dropzone@3.10.2
          found: dropzone@3.10.2
        install: import-style@1.0.0
          found: import-style@1.0.0
        install: arale-widget@1.2.0
          found: arale-widget@1.2.0
        install: seajs-css@1.0.2
          found: seajs-css@1.0.2
        install: jquery.rails@0.1.0
          found: jquery.rails@0.1.0
no matched version of jquery:
Error: no matched version of jquery
    at resolveDeps (/usr/local/lib/node_modules/spm/node_modules/father/lib/spm-package.js:118:11)
    at /usr/local/lib/node_modules/spm/node_modules/father/lib/spm-package.js:93:18
    at Array.forEach (native)
    at parseDeps (/usr/local/lib/node_modules/spm/node_modules/father/lib/spm-package.js:92:4)
    at SubClass.Package.extend.readPackage (/usr/local/lib/node_modules/spm/node_modules/father/lib/spm-package.js:20:5)
    at SubClass.Class.create._parse (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:93:20)
    at SubClass.Class.create.initialize (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:45:10)
    at new SubClass (/usr/local/lib/node_modules/spm/node_modules/father/node_modules/arale/lib/class.js:53:23)
    at /usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:303:22
    at Array.forEach (native):
```

**Comment by sorrycc** [comment]
本地在一个文件里 require 了上面的所有模块，没有出错。建议：

1. 重装 spm 试试
1. `DEBUG=father* spm build` 看下 debug 信息是否能定位到问题

**Comment by alvin2ye** [comment]
我再提供1个办法 rm -rf spm_modules 再1个1个加进来就好了. 中间还升级了  spm 最终解决了, 但是没有找到问题.

**Comment by popomore** [comment]
这个是说没找到匹配的 jquery 版本

**Comment by alvin2ye** [comment]
@popomore 我grep 过, 安装了所有版本的jquery 一样的提示

**Comment by popomore** [comment]
是不是 jquery 配的 *

**Comment by alvin2ye** [comment]
之前有个包配置成 * 了, 现在这个问题已经不能重现了. 谢谢你.

**Comment by popomore** [comment]
那就是已知问题 #1104

**Comment by alvin2ye** [comment]
bingo
