### ISSUE TITLE
spm-client generator 实现的兼容性问题

### ISSUE THREAD

**Issue by afc163** [spmjs/spm#1161]
master 分支
node@0.10.33

```
🎯   spm@3.4.0-dev git:❨master❩ spm ls

/Users/afc163/Projects/spm/node_modules/spm-client/lib/publish.js:30
module.exports = function* publish(args, config) {
                         ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/afc163/Projects/spm/node_modules/spm-client/index.js:4:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by popomore** [comment]
@sorrycc 这个没加 gnode

**Comment by sorrycc** [comment]
加漏了。。
