### ISSUE TITLE
spm@ninja Win7 下不能使用

### ISSUE THREAD

**Issue by airyland** [spmjs/spm#1186]
3.4.0-rc1

Windows7 下根本不能用。包括install, publish 等命令。

```shell
'c:\Users\Administrator\AppData\Roaming\npm\node_modules\spm\bin\spm-publish' �����ڲ����ⲿ���Ҳ���ǿ��
��еĳ���
�������ļ�
Possibly unhandled Error: [object Object]
    at Object.ret.isClass [as ensureErrorObject] (c:\Users\Administrator\AppData\Roaming\npm\node_modules\spm\node_modul
es\exeq\node_modules\bluebird\js\main\util.js:229:20)
    at Promise._rejectCallback (c:\Users\Administrator\AppData\Roaming\npm\node_modules\spm\node_modules\exeq\node_modul
es\bluebird\js\main\promise.js:436:22)
    at c:\Users\Administrator\AppData\Roaming\npm\node_modules\spm\node_modules\exeq\node_modules\bluebird\js\main\promi
se.js:454:17
    at ChildProcess.<anonymous> (c:\Users\Administrator\AppData\Roaming\npm\node_modules\spm\node_modules\exeq\index.js:
43:14)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

**Comment by sorrycc** [comment]
试试 3.4.0-rc2，windows 下可以用了。
