### ISSUE TITLE
build 时出这种错误, 不知道怎么排除

### ISSUE THREAD

**Issue by alvin2ye** [spmjs/spm#1191]
```
      installed: $CWD/spm_modules/jquery/1.8.3
        extract: ~/.spm/cache/emitter-1.1.2.tar.gz
      installed: $CWD/spm_modules/emitter/1.1.2
        extract: ~/.spm/cache/jquery-1.7.2.tar.gz
      installed: $CWD/spm_modules/jquery/1.7.2
        extract: ~/.spm/cache/arale-base-1.2.0.tar.gz
      installed: $CWD/spm_modules/arale-base/1.2.0
        depends: arale-class@1.2.0, arale-events@1.2.0
        install: arale-class@1.2.0
          found: arale-class@1.2.0
        install: arale-events@1.2.0
        extract: ~/.spm/cache/arale-events-1.2.0.tar.gz
      installed: $CWD/spm_modules/arale-events/1.2.0
        extract: ~/.spm/cache/handlebars-1.3.0.tar.gz
      installed: $CWD/spm_modules/handlebars/1.3.0
source-map is not in dependencies but required by spm_modules/handlebars/2.0.0/dist/cjs/handlebars/compiler/code-gen.js:
Error: source-map is not in dependencies but required by spm_modules/handlebars/2.0.0/dist/cjs/handlebars/compiler/code-gen.js
    at getDepFile (/home/deployer/npm-global/lib/node_modules/spm/node_modules/father/lib/package.js:212:11)
    at /home/deployer/npm-global/lib/node_modules/spm/node_modules/father/lib/package.js:170:17
    at Array.forEach (native)
    at lookupDeps (/home/deployer/npm-global/lib/node_modules/spm/node_modules/father/lib/package.js:154:4)
    at /home/deployer/npm-global/lib/node_modules/spm/node_modules/father/lib/package.js:181:5
    at Array.forEach (native)
    at lookupDeps (/home/deployer/npm-global/lib/node_modules/spm/node_modules/father/lib/package.js:154:4)
    at /home/deployer/npm-global/lib/node_modules/spm/node_modules/father/lib/package.js:181:5
    at Array.forEach (native)
    at lookupDeps (/home/deployer/npm-global/lib/node_modules/spm/node_modules/father/lib/package.js:154:4):
```

vi package.json
```
{
  "name": "wzgd",
  "version": "0.0.1",
  "description": "Wzgd",
  "keywords": [],
  "homepage": "",
  "author": "alvin2ye <alvin.ye.cn@gmail.com>",
  "repository": {
    "type": "git",
    "url": ""
  },
  "bugs": {
    "url": ""
  },
  "licenses": "MIT",
  "spm": {
    "output": [
      "app/*.js",
      "app/**/*.js",
      "app/**/*.html",
      "app/**/*.tpl",
      "app/**/**/**.html"
    ],
    "dependencies": {
      "seajs": "2.3.0",
      "seajs-wrap2": "1.0.2",
      "jquery": "2.1.1",
      "jquery-ui": "1.11.1",
      "jquery.jarvismenu": "0.0.2",
      "smartadmin-bootstrap": "0.0.1",
      "jqgrid": "4.6.0",
      "moment": "2.9.0",
      "arale-class": "1.2.0",
      "jquery.summernote": "0.1.0",
      "xs.art-template": "3.0.0",
      "at2": "0.5.2",
      "seajs-text": "1.1.0",
      "easy-pagination2": "1.0.2",
      "dropzone": "3.10.2",
      "import-style": "1.0.0",
      "arale-widget": "1.2.0",
      "seajs-css": "1.0.2",
      "jquery.rails": "0.1.2",
      "recordselect": "0.1.5",
      "arale-dialog": "1.5.0",
      "handlebars-runtime": "1.3.0",
      "arale-messenger": "2.1.0",
      "arale-overlay": "1.2.0",
      "arale-templatable": "0.10.0",
      "handlebars": "2.0.0",
      "arale-iframe-shim": "1.1.0",
      "position": "1.1.0",
      "source-map": "1.0.2",
      "jquery.serialize-hash": "0.0.1",
      "numeral": "1.5.3"
    },
    "devDependencies": {
      "expect.js": "0.3.1"
    }
  }
}
```

**Comment by alvin2ye** [comment]
```
spm build --include all --ignore "jquery,jquery-ui" -O ./dist
```

**Comment by sorrycc** [comment]
好像是 handlebars@2.0.0 的问题，@popomore

**Comment by popomore** [comment]
可以先配置一个 skip `--skip source-map`

handlebars 这里有 try/catch 估计浏览器是不用这个库的。

是不是考虑构建信息优先读取当前包的。

**Comment by sorrycc** [comment]
`skip source-map` 或者用 handlebars@1.3.0 吧。

**Comment by cxc3214** [comment]
1.3.0 报这个错误 Handlebars.registerHelper is not a function
