### ISSUE TITLE
3.4.0-rc2  Win7下两个问题

### ISSUE THREAD

**Issue by airyland** [spmjs/spm#1192]
一、 这个版本依赖了pangyp,而它要求安装python(https://github.com/rvagg/pangyp)

查了一下是： spm-client 依赖了 6to5 依赖了 kexec 依赖了 pangyp

而且要自己手动全局安装 pangyp，否则报 pangyp命令不存在。

手动安装后，报python不存在。

```shell

> kexec@1.1.0 install C:\Users\Administrator\AppData\Roaming\npm\node_modules\spm\node_modules\spm-client\node_modules\6
to5\node_modules\kexec
> pangyp configure build

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (c:\Users\Administrator\AppData\Roaming\npm\node_modules\pangyp\lib\configure.js:103:
14)
gyp ERR! stack     at c:\Users\Administrator\AppData\Roaming\npm\node_modules\pangyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:108:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\pangyp\\bin\\node-gyp.js" "confi
gure" "build"
gyp ERR! cwd C:\Users\Administrator\AppData\Roaming\npm\node_modules\spm\node_modules\spm-client\node_modules\6to5\node_
modules\kexec
gyp ERR! node -v v0.10.35
gyp ERR! pangyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing kexec@1.1.0
npm WARN optional dep failed, continuing fsevents@0.3.5
```
这样真的ok? 

二、如果不安装node的不稳定版本到0.11.13以上，build的时候就一定会报错。官方提供下载的稳定版本才0.10.36。所以这里是默认大家都会安装了node>=0.11.13版本？co只是显示了WARNING，但是 co的问题导致直接导致build和publish不了。

```shell
c:\Users\Administrator\AppData\Roaming\npm\node_modules\spm\node_modules\scripts-hook\node_modules\co\index.js:47
  return new Promise(function(resolve, reject) {
             ^
ReferenceError: Promise is not defined
    at co (c:\Users\Administrator\AppData\Roaming\npm\node_modules\spm\node_modules\scripts-hook\node_modules\co\index.j
s:47:14)
    at module.exports (c:\Users\Administrator\AppData\Roaming\npm\node_modules\spm\node_modules\scripts-hook\index.js:14
:10)
    at Object.<anonymous> (c:\Users\Administrator\AppData\Roaming\npm\node_modules\spm\node_modules\spm-build\cli.js:86:
1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (c:\Users\Administrator\AppData\Roaming\npm\node_modules\spm\bin\spm-build:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

```

今天在机子上是node=0.10.35这个版本的时候，我企图回退版本：

3.4.0-rc2使用时报错
3.4.0-rc1使用时报错
stable的版本有bug，相对路径引用的bug
3.3.3的版本的找不到
3.3.2的版本使用时报错
3.3.1的版本使用时报错
3.3.0的版本也是有相对路径的bug
。
。
所以最终我放弃了，在本地更改了spm的那几行有问题的代码。

所以我在想，SPM是不是每次要发布时看看Mac过了测试就直接发了，至于Windows等着别人装了报错再修复。说完了。

**Comment by sorrycc** [comment]
抱歉。rc2 win 下只测了 node 0.11，忘记测 0.10 了。

**Comment by afc163** [comment]
默认安上 bluebird 吧。@sorrycc

**Comment by sorrycc** [comment]
不是 bluebird 的问题。scripts-hook 依赖的 co 用了 Promise 了，现在用的 gnode 不支持 Promise ，我换成 6to5 应该就可以了。

**Comment by afc163** [comment]
好。

**Comment by popomore** [comment]
貌似我周报里有发过

https://github.com/facebook/regenerator/releases/tag/v0.8.0

**Comment by sorrycc** [comment]
- 第一个 python 的报错貌似不影响，测试了 spm-client 相关的功能没有问题
- publish 和 build 的问题解决了，发了 `3.4.0-rc4`

**Comment by airyland** [comment]
thx
