### ISSUE TITLE
Unhandled stream error in pipe. 是网络问题吗？

### ISSUE THREAD

**Issue by zhishaofei3** [spmjs/spm#1194]
是网络问题吗？
````
$ spm install

        install: expect.js@0.3.1
        install: jquery@1.8.3
        install: moment@2.6.0
       download: http://spmjs.io/repository/expect.js/0.3.1/expect.js-0.3.1.tar.gz

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: read ECONNRESET
    at errnoException (net.js:905:11)
    at TCP.onread (net.js:559:19)
````

**Comment by sorrycc** [comment]
看出错是网络问题，重试下好了吗?
