### ISSUE TITLE
新版本spm打包出错, 老版本打包正常.

### ISSUE THREAD

**Issue by wuguanghai45** [spmjs/spm#1206]
/home/deployer/npm-global/lib/node_modules/spm/node_modules/spm-build/node_modules/gulp-spm/lib/common.js:145
      return callback(new Error('extension "' + ext + '" not supported.'));
                      ^
Error: extension "gif" not supported.
    at DestroyableTransform._transform (/home/deployer/npm-global/lib/node_modules/spm/node_modules/spm-build/node_modules/gulp-spm/lib/common.js:145:23)
    at DestroyableTransform.Transform._read (/home/deployer/npm-global/lib/node_modules/spm/node_modules/spm-build/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/home/deployer/npm-global/lib/node_modules/spm/node_modules/spm-build/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/deployer/npm-global/lib/node_modules/spm/node_modules/spm-build/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/deployer/npm-global/lib/node_modules/spm/node_modules/spm-build/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/home/deployer/npm-global/lib/node_modules/spm/node_modules/spm-build/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/home/deployer/npm-global/lib/node_modules/spm/node_modules/spm-build/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/home/deployer/npm-global/lib/node_modules/spm/node_modules/spm-build/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/home/deployer/npm-global/lib/node_modules/spm/node_modules/spm-build/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:92:17)
    at emitReadable_ (/home/deployer/npm-global/lib/node_modules/spm/node_modules/spm-build/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/home/deployer/npm-global/lib/node_modules/spm/node_modules/spm-build/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)

**Comment by sorrycc** [comment]
试了下 output 里包含 gif 文件不会报错。给个能重现的代码包?

**Comment by wuguanghai45** [comment]
https://github.com/alvin2ye/spm-recordselect 
这个包新版本打包出错．．老版本打包是好的

**Comment by wuguanghai45** [comment]
是不是　3.4　对图片进行了一些处理造成的啊．．

**Comment by sorrycc** [comment]
已发布 spm 3.4.2，build 不会报错了。js require css 时处理图片路径有些麻烦，这种情况暂不处理 css 引用的资源文件。
