### ISSUE TITLE
我想打包 github.com/knsv/mermaid 这个库 应该怎么做.

### ISSUE THREAD

**Issue by alvin2ye** [spmjs/spm#1210]
发现他依赖he, 有发现原库中得he错了, 自己传了个 he2, 
又发现依赖d3, 有传了个d3
又发现 dagre-d3 ~~

来来回回折腾了很久.

有没有办法可以把原来依赖requirejs 的库很快的移植到spm上.

**Comment by afc163** [comment]
这个库依赖 AMD 是什么意思？看了下源码是 CommonJS 的，基本可以直接发布到 spm 上。https://github.com/knsv/mermaid/blob/master/src/main.js

移植可以参考 [迁移业界优秀模块到 spmjs.io 并反推的简易教程](https://github.com/spmjs/spm/wiki/%E8%BF%81%E7%A7%BB%E4%B8%9A%E7%95%8C%E4%BC%98%E7%A7%80%E6%A8%A1%E5%9D%97%E5%88%B0-spmjs.io-%E5%B9%B6%E5%8F%8D%E6%8E%A8%E7%9A%84%E7%AE%80%E6%98%93%E6%95%99%E7%A8%8B)

**Comment by afc163** [comment]
另外 he 和 d3 有具体什么问题，可以发 issue 联系我们进行修复。

**Comment by alvin2ye** [comment]
@afc163 我之前就试过, 不行才发这个issue 的. 难道 spm 部分写错?

**Comment by alvin2ye** [comment]
he 部分已经创建  #1211

**Comment by sorrycc** [comment]
搞定了吗?

**Comment by alvin2ye** [comment]
@sorrycc 没有, 各种问题.  :(

**Comment by afc163** [comment]
你 publish 时不需要自己建目录结构和打包的，直接 clone 它原来的仓库就可以了。要不 @sorrycc 来帮忙搞一下吧。

**Comment by alvin2ye** [comment]
@afc163 恩, 就是这样, 我遇到一个require 打1个包,  打包遇到问题, 有要解决. 最后只有 gg了.
有 @sorrycc 帮忙最好 :), 期待分享下过程.

**Comment by afc163** [comment]
过程就是我发的迁移教程啊。。。:sad:

**Comment by alvin2ye** [comment]
## vi package.json

```
   },
+  "spm": {
+    "main": "src/main.js",
+    "dependencies": {
+    },
+    "devDependencies": {
+      "expect.js": "0.3.1"
+    }
+  },
   "devDependencies": {
     "async": "^0.9.0",
```
     
## spm build 得到错误


```
fs is not in dependencies but required by src/diagrams/flowchart/parser/flow.js:
Error: fs is not in dependencies but required by src/diagrams/flowchart/parser/flow.js
    at getDepFile (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:212:11)
    at /usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:170:17
    at Array.forEach (native)
    at lookupDeps (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:154:4)
    at /usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:181:5
    at Array.forEach (native)
```

## spm install fs -S

## spm build 得到错误


```
path is not in dependencies but required by src/diagrams/flowchart/parser/flow.js:
Error: path is not in dependencies but required by src/diagrams/flowchart/parser/flow.js
    at getDepFile (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:212:11)
    at /usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:170:17
    at Array.forEach (native)
    at lookupDeps (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:154:4)
    at /usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:181:5
    at Array.forEach (native)
    at lookupDeps (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:154:4)
    at SubClass.<anonymous> (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:119:7)
    at Array.forEach (native)
```

## spm install path -S

## spm build 得到错误


```
dagre-d3 is not in dependencies but required by src/diagrams/flowchart/dagre-d3.js:
Error: dagre-d3 is not in dependencies but required by src/diagrams/flowchart/dagre-d3.js
    at getDepFile (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:212:11)
    at /usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:170:17
    at Array.forEach (native)
    at lookupDeps (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:154:4)
    at /usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:181:5
    at Array.forEach (native)
    at lookupDeps (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:154:4)
    at /usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:181:5
    at Array.forEach (native)
```

# spm install dagre-d3 -S

```
         target: http://spmjs.io
        install: dagre-d3@stable
           exit: Not found. ~ http://spmjs.io/repository/dagre-d3/
```

# 接下来进入第1个循环

```
git clone git@github.com:cpettitt/dagre-d3.git
```
发现这个库改起来也一样麻烦 ~~

**Comment by sorrycc** [comment]
fs, path 这些依赖库都是 @hotoo 占坑的，还没填。源码不好迁的话，直接迁 dist 文件试试? https://github.com/knsv/mermaid/tree/master/dist

**Comment by alvin2ye** [comment]
@sorrycc 试过 里面有大量的
![image](https://cloud.githubusercontent.com/assets/5401/6409827/6fbca5ea-bea3-11e4-8a61-206c1a0aae87.png)

![image](https://cloud.githubusercontent.com/assets/5401/6409844/a49852a0-bea3-11e4-955b-bb4b954a45d7.png)

跑不起来

**Comment by afc163** [comment]
试试 skip

**Comment by alvin2ye** [comment]
@afc163 gurp + bowerfliy 超方便, 主要是原作者支持,  哎我动摇了 ~~~

**Comment by afc163** [comment]
两个词都打错了。。。去用吧的确方便。

**Comment by hotoo** [comment]
浏览器版 fs 怎么搞？

**Comment by hotoo** [comment]
node 原生模块同名坑都加了 @sorrycc 
http://spmjs.io/account/sorrycc

**Comment by alvin2ye** [comment]
@afc163 对打错了, 我不熟. spm和seajs 倒是用了好几个月了

我同事 gulp + browserify  打包 mermaid 几分钟. 

我却用SPM N天了. SO ~~ 我不知道是哪里出了问题. 不都是CommonJS . 

差距咋这么大呢, 有可能是我的问题.
