### ISSUE TITLE
安装spm出错

### ISSUE THREAD

**Issue by zjgnlzq** [spmjs/spm#1215]
```bash
C:\Users\andy>npm install -g spm
npm WARN deprecated 6to5@3.3.12: 6to5 is now 'babel': https://babeljs.io/blog/2015/02/15/not-born-to-die
npm WARN engine co@4.1.0: wanted: {"node":">= 0.11.13"} (current: {"node":"0.10.35","npm":"1.4.28"})
npm WARN deprecated 6to5@2.13.7: 6to5 is now 'babel': https://babeljs.io/blog/2015/02/15/not-born-to-die
npm WARN engine co@4.1.0: wanted: {"node":">= 0.11.13"} (current: {"node":"0.10.35","npm":"1.4.28"})
npm WARN engine co@4.1.0: wanted: {"node":">= 0.11.13"} (current: {"node":"0.10.35","npm":"1.4.28"})
npm WARN deprecated swig@0.14.0: v1.0.0 is a complete rewrite of Swig from the ground up. Previous versions are no longer supported
npm WARN optional dep failed, continuing fsevents@0.3.5
-


> kexec@1.1.0 install C:\Users\andy\AppData\Roaming\npm\node_modules\spm\node_modules\spm-client\node_modules\6to5\node_modules\kexec
> pangyp configure build

'pangyp' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm WARN optional dep failed, continuing kexec@1.1.0
npm WARN optional dep failed, continuing fsevents@0.3.5
\


> kexec@1.0.0 install C:\Users\andy\AppData\Roaming\npm\node_modules\spm\node_modules\6to5\node_modules\kexec
> node-gyp configure build


C:\Users\andy\AppData\Roaming\npm\node_modules\spm\node_modules\6to5\node_modules\kexec>node "D:\wangyi\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (D:\wangyi\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at D:\wangyi\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:108:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "D:\\wangyi\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\andy\AppData\Roaming\npm\node_modules\spm\node_modules\6to5\node_modules\kexec
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing kexec@1.0.0
```

##  环境如下
os: win7 64位
node: 0.10.35
npm: 1.4.28

**Comment by popomore** [comment]
都是 optional dep 吧，安装不成功？

**Comment by zjgnlzq** [comment]
不稳定，有时安装成功，有时安装不了

**Comment by popomore** [comment]
这个报错应该不影响使用的

**Comment by zjgnlzq** [comment]
恩

**Comment by zjgnlzq** [comment]
##  有时报错，安装不了，报错内容如下
```bash
C:\Users\andy\Desktop>npm install -g spm --registry=https://registry.npm.taobao.org
npm WARN deprecated 6to5@3.3.12: 6to5 is now 'babel': https://babeljs.io/blog/2015/02/15/not-born-to-die
npm WARN engine co@4.1.0: wanted: {"node":">= 0.11.13"} (current: {"node":"0.10.35","npm":"1.4.28"})
npm WARN deprecated 6to5@2.13.7: 6to5 is now 'babel': https://babeljs.io/blog/2015/02/15/not-born-to-die
npm WARN engine co@4.1.0: wanted: {"node":">= 0.11.13"} (current: {"node":"0.10.35","npm":"1.4.28"})
npm WARN engine co@4.1.0: wanted: {"node":">= 0.11.13"} (current: {"node":"0.10.35","npm":"1.4.28"})
npm WARN deprecated swig@0.14.0: v1.0.0 is a complete rewrite of Swig from the ground up. Previous versions are no longer supported
|


> kexec@1.1.0 install C:\Users\andy\AppData\Roaming\npm\node_modules\spm\node_modules\spm-client\node_modules\6to5\node_modules\kexec
> pangyp configure build

'pangyp' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm WARN optional dep failed, continuing kexec@1.1.0
npm WARN optional dep failed, continuing fsevents@0.3.5
npm WARN optional dep failed, continuing fsevents@0.3.5
\


> kexec@1.0.0 install C:\Users\andy\AppData\Roaming\npm\node_modules\spm\node_modules\6to5\node_modules\kexec
> node-gyp configure build


C:\Users\andy\AppData\Roaming\npm\node_modules\spm\node_modules\6to5\node_modules\kexec>node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp
-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build
gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.3.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:108:14)
gyp ERR! stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:97:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:656:7)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:766:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\andy\AppData\Roaming\npm\node_modules\spm\node_modules\6to5\node_modules\kexec
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing kexec@1.0.0
/
> phantomjs@1.9.15 install C:\Users\andy\AppData\Roaming\npm\node_modules\spm\node_modules\phantomjs
> node install.js

Download already available at C:\Users\andy\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Extracting zip contents
Removing C:\Users\andy\AppData\Roaming\npm\node_modules\spm\node_modules\phantomjs\lib\phantom
Copying extracted folder C:\Users\andy\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1425394954494\phantomjs-1.9.8-windows -> C:
\Users\andy\AppData\Roaming\npm\node_modules\spm\node_modules\phantomjs\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\Users\andy\AppData\Roaming\npm\node_modules\spm\node_modules\phantomjs\lib\phantom\phantomjs.exe
npm ERR! EEXIST, open 'C:\Users\andy\AppData\Roaming\npm-cache\33613c70-he-source-map-0-1-43-package-tgz.lock'
File exists: C:\Users\andy\AppData\Roaming\npm-cache\33613c70-he-source-map-0-1-43-package-tgz.lock
Move it away, and try again.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "D:\\Program Files\\nodejs\\\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "spm" "--regis
try=https://registry.npm.taobao.org"
npm ERR! cwd C:\Users\andy\Desktop
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! path C:\Users\andy\AppData\Roaming\npm-cache\33613c70-he-source-map-0-1-43-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! not ok code 0
```

##  根据报错
```bash
npm ERR! EEXIST, open 'C:\Users\andy\AppData\Roaming\npm-cache\33613c70-he-source-map-0-1-43-package-tgz.lock'
File exists: C:\Users\andy\AppData\Roaming\npm-cache\33613c70-he-source-map-0-1-43-package-tgz.lock
Move it away, and try again.
```
运行```npm cache clean```,把C:\Users\andy\AppData\Roaming\npm-cache文件夹清空了，再安装还是不行，报同样的错误。

**Comment by sorrycc** [comment]
解决了吗? 手动删除 `C:\Users\andy\AppData\Roaming\npm-cache` 这个目录也不行?

**Comment by sorrycc** [comment]
今天在 win 下安装过多次，都没有出现类似问题。。

**Comment by afc163** [comment]
可以参考下这里：https://github.com/rvagg/pangyp#installation

**Comment by zjgnlzq** [comment]
好的，我再试试

**Comment by nimojs** [comment]
:neckbeard:  我也遇到过，最后用代理安装解决了。不知道是不是跟楼主相同的情况。
