### ISSUE TITLE
有没有人将sjcj移植到spm库里面吗？或者怎么在commonjs里引用外部压缩之后的js？

### ISSUE THREAD

**Issue by fly3q** [spmjs/spm#1235]
原因是用rncryptor（https://github.com/RNCryptor/rncryptor-js）
做跨语言的加解密，
发现这个js版本依赖于sjsl（https://github.com/bitwiseshiftleft/sjcl）
但是这个sjsl编译之后不能直接放到commonjs里面使用！
或者在spm3里面怎么引用外部压缩之后的js库？

**Comment by sorrycc** [comment]
为啥不能直接放到 commonjs 里使用? sjsl 编译之后是什么样的?

**Comment by sorrycc** [comment]
试着在迁移 sjsl 的时候手动加一个 `module.exports = sjsl` ?

**Comment by fly3q** [comment]
我是直接把编译完之后的sjsl代码嵌在rncryptor.js里面，
最终在spm build -s 的时候报错说：
crypto is not in dependencies but required by rncryptor.js: 
Error: crypto is not in dependencies but required by rncryptor.js
    at getDepFile (/usr/lib/node_modules/spm/node_modules/spm-build/node_modules/father/lib/package.js:212:11)
    at /usr/lib/node_modules/spm/node_modules/spm-build/node_modules/father/lib/package.js:170:17
    at Array.forEach (native)
    at lookupDeps (/usr/lib/node_modules/spm/node_modules/spm-build/node_modules/father/lib/package.js:154:4)
    at /usr/lib/node_modules/spm/node_modules/spm-build/node_modules/father/lib/package.js:181:5
    at Array.forEach (native)
    at lookupDeps (/usr/lib/node_modules/spm/node_modules/spm-build/node_modules/father/lib/package.js:154:4)
    at /usr/lib/node_modules/spm/node_modules/spm-build/node_modules/father/lib/package.js:181:5
    at Array.forEach (native)
    at lookupDeps (/usr/lib/node_modules/spm/node_modules/spm-build/node_modules/father/lib/package.js:154:4):

这个sjsl编译之后，是经过压缩的，里面有含有require("crypto")这样的代码。

**Comment by sorrycc** [comment]
build 的时候加上 `--skip crypto`

**Comment by fly3q** [comment]
这样子是可以了，谢谢了。
