### ISSUE TITLE
引用ES6写法的react组件　rc-tabs出错

### ISSUE THREAD

**Issue by wuguanghai45** [spmjs/spm#1240]
Uncaught SyntaxError: Unexpected reserved word

http://spmjs.io/package/rc-tabs

**Comment by wuguanghai45** [comment]
如果把组件的源代码直接拷出来可以用，用ES6，除了6to5 外还需要别的配置

**Comment by wuguanghai45** [comment]
spmio上面的rc-tabs用spm-server返回的头没有进行ES6处理

define('rc-tabs/3.1.0/lib/Tabs', function(require, exports, module){
/** @jsx React.DOM */

var React = require("react/0.13.1/react.js");

var keyCode = {
  /**
   * LEFT
   */
  LEFT: 37, // also NUM_WEST
  /**
   * UP
   */
  UP: 38, // also NUM_NORTH
  /**
   * RIGHT
   */
  RIGHT: 39, // also NUM_EAST
  /**
   * DOWN
   */
  DOWN: 40 // also NUM_SOUTH
};

class TabPane extends React.Component {
  constructor(props) {
    super(props);
    this.prefixClsFn = prefixClsFn.bind(this);
    this.state = {
      prefixCls: props.rootPrefixCls + '-tabpane'
    };
  }

**Comment by wuguanghai45** [comment]
我把代码拷出来进行相对路径的require
头文件如下，代码正常运行
define('app/extra/rc-tabs', function(require, exports, module){
"use strict";

var _prototypeProperties = function (child, staticProps, instanceProps) { if (staticProps) Object.defineProperties(child, staticProps); if (instanceProps) Object.defineProperties(child.prototype, instanceProps); };

var _get = function get(object, property, receiver) { var desc = Object.getOwnPropertyDescriptor(object, property); if (desc === undefined) { var parent = Object.getPrototypeOf(object); if (parent === null) { return undefined; } else { return get(parent, property, receiver); } } else if ("value" in desc && desc.writable) { return desc.value; } else { var getter = desc.get; if (getter === undefined) { return undefined; } return getter.call(receiver); } };

var _inherits = function (subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) subClass.__proto__ = superClass; };

var _classCallCheck = function (instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } };

/** @jsx React.DOM */

var React = require("react/0.13.1/react.js");

**Comment by wuguanghai45** [comment]
但是spm build 的时候出错
我单个打包了一下rc-tabs还是出错。
错误提示如下

/home/wgh/spm/tabs/rc-tabs/3.1.0/index.js: Unexpected token: name (TabPane): 
Error
    at new JS_Parse_Error (/home/wgh/npm-global/lib/node_modules/spm/node_modules/spm-build/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:189:18)
    at js_error (/home/wgh/npm-global/lib/node_modules/spm/node_modules/spm-build/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:197:11)
    at croak (/home/wgh/npm-global/lib/node_modules/spm/node_modules/spm-build/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:660:41)
    at token_error (/home/wgh/npm-global/lib/node_modules/spm/node_modules/spm-build/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:664:9)
    at unexpected (/home/wgh/npm-global/lib/node_modules/spm/node_modules/spm-build/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:670:9)
    at semicolon (/home/wgh/npm-global/lib/node_modules/spm/node_modules/spm-build/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:690:43)
    at simple_statement (/home/wgh/npm-global/lib/node_modules/spm/node_modules/spm-build/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:864:73)
    at /home/wgh/npm-global/lib/node_modules/spm/node_modules/spm-build/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:737:19
    at /home/wgh/npm-global/lib/node_modules/spm/node_modules/spm-build/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:703:24
    at block_ (/home/wgh/npm-global/lib/node_modules/spm/node_modules/spm-build/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:977:20):

**Comment by wuguanghai45** [comment]
spm 版本　3.4.3

**Comment by sorrycc** [comment]
rc-tabs 用了 es6 的特性，现在转换的时候没加 harmony 参数。等 spm 3.5 吧，会一起修复掉。

**Comment by sorrycc** [comment]
已支持，请升级到 3.6 。
