### ISSUE TITLE
require 一个非 install来的本地lib文件，如何操作？

### ISSUE THREAD

**Issue by lrn744809337** [spmjs/spm#1245]
```
../../lib/lib4t/abc is out of bound: 
Error: ../../lib/lib4t/abc is out of bound
    at resolvePath (/usr/local/lib/node_modules/spm/node_modules/father/lib/util.js:70:35)
    at /usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:180:27
    at Array.forEach (native)
    at lookupDeps (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:154:4)
    at SubClass.<anonymous> (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:119:7)
    at Array.forEach (native)
    at SubClass.Class.create._parseFiles (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:117:34)
    at SubClass.Class.create._parse (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:98:10)
    at SubClass.Class.create.initialize (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:45:10)
    at new SubClass (/usr/local/lib/node_modules/spm/node_modules/father/node_modules/arale/lib/class.js:53:23): 
```

**Comment by sorrycc** [comment]
现在主干上的版本已经可以 require pkg 外的文件了，还没发布。

**Comment by lrn744809337** [comment]
就是说 git 下来 ，然后 npm install -g 
然后想确认下git上的这个版本 我spm -v 后是 3.3.4  ？？？
再然后 require() 外部文件 的 具体语法是怎样的？

**Comment by sorrycc** [comment]
- git 下来，然后 `npm link` 就会被装到全局了。
- require 外部文件之前我试过用相对路径是可以的。
