### ISSUE TITLE
spm 安装失败!

### ISSUE THREAD

**Issue by yqfang** [spmjs/spm#1247]
系统: ubuntu, 内核版本: 3.19.3-031903-generic
cnpm 和npm 都试过了

```
npm install -g spm
[sudo] password for yqfang: 
npm WARN deprecated 6to5@3.3.12: 6to5 is now 'babel': https://babeljs.io/blog/2015/02/15/not-born-to-die
npm WARN deprecated 6to5-core@2.13.7: 6to5 is now 'babel': https://babeljs.io/blog/2015/02/15/not-born-to-die
npm WARN deprecated 6to5-core@3.6.5: 6to5 is now 'babel': https://babeljs.io/blog/2015/02/15/not-born-to-die
npm WARN deprecated swig@0.14.0: v1.0.0 is a complete rewrite of Swig from the ground up. Previous versions are no longer supported
 
> kexec@1.0.0 install /usr/local/lib/node_modules/spm/node_modules/6to5/node_modules/kexec
> node-gyp configure build

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/usr/local/lib/node_modules/spm/node_modules/6to5/node_modules/kexec/build'
  CXX(target) Release/obj.target/kexec/src/kexec.o
../src/kexec.cc: In function ‘int clear_cloexec(int)’:
../src/kexec.cc:22:30: error: ‘F_GETFD’ was not declared in this scope
     int flags = fcntl (desc, F_GETFD, 0);
                              ^
../src/kexec.cc:22:40: error: ‘fcntl’ was not declared in this scope
     int flags = fcntl (desc, F_GETFD, 0);
                                        ^
../src/kexec.cc:26:15: error: ‘FD_CLOEXEC’ was not declared in this scope
     flags &= ~FD_CLOEXEC; //clear FD_CLOEXEC bit
               ^
../src/kexec.cc:27:25: error: ‘F_SETFD’ was not declared in this scope
     return fcntl (desc, F_SETFD, flags);
                         ^
../src/kexec.cc: At global scope:
../src/kexec.cc:43:34: error: ‘Arguments’ does not name a type
 static Handle<Value> kexec(const Arguments& args) {
                                  ^
In file included from ../src/kexec.cc:2:0:
/home/yqfang/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> kexec(const int&)’:
/home/yqfang/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/kexec.cc:44:17: error: within this context
     HandleScope scope;
                 ^
../src/kexec.cc:67:20: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
     if ( 1 == args.Length() && args[0]->IsString() )
                    ^
../src/kexec.cc:67:38: error: invalid types ‘const int[int]’ for array subscript
     if ( 1 == args.Length() && args[0]->IsString() )
                                      ^
../src/kexec.cc:69:39: error: invalid types ‘const int[int]’ for array subscript
         String::Utf8Value v8str(args[0]);
                                       ^
../src/kexec.cc:78:44: error: no matching function for call to ‘v8::Number::New(int&)’
         Local<Number> num = Number::New(err);
                                            ^
../src/kexec.cc:78:44: note: candidate is:
In file included from ../src/kexec.cc:2:0:
/home/yqfang/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/yqfang/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../src/kexec.cc:79:22: error: ‘class v8::HandleScope’ has no member named ‘Close’
         return scope.Close(num/*Undefined()*/);
                      ^
../src/kexec.cc:83:20: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
     if ( 2 == args.Length() && args[0]->IsString() && args[1]->IsArray() )
                    ^
../src/kexec.cc:83:38: error: invalid types ‘const int[int]’ for array subscript
     if ( 2 == args.Length() && args[0]->IsString() && args[1]->IsArray() )
                                      ^
../src/kexec.cc:83:61: error: invalid types ‘const int[int]’ for array subscript
     if ( 2 == args.Length() && args[0]->IsString() && args[1]->IsArray() )
                                                             ^
../src/kexec.cc:85:39: error: invalid types ‘const int[int]’ for array subscript
         String::Utf8Value v8str(args[0]);
                                       ^
../src/kexec.cc:89:61: error: invalid types ‘const int[int]’ for array subscript
         Local<Array> argv_handle = Local<Array>::Cast(args[1]);
                                                             ^
../src/kexec.cc:101:66: error: no matching function for call to ‘v8::Integer::New(int&)’
             String::Utf8Value arg(argv_handle->Get(Integer::New(i))->ToString());
                                                                  ^
../src/kexec.cc:101:66: note: candidate is:
In file included from ../src/kexec.cc:2:0:
/home/yqfang/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/yqfang/.node-gyp/0.12.0/deps/v8/include/v8.h:2012:25: note:   candidate expects 2 arguments, 1 provided
../src/kexec.cc:118:44: error: no matching function for call to ‘v8::Number::New(int&)’
         Local<Number> num = Number::New(err);
                                            ^
../src/kexec.cc:118:44: note: candidate is:
In file included from ../src/kexec.cc:2:0:
/home/yqfang/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/yqfang/.node-gyp/0.12.0/deps/v8/include/v8.h:1999:24: note:   candidate expects 2 arguments, 1 provided
../src/kexec.cc:119:22: error: ‘class v8::HandleScope’ has no member named ‘Close’
         return scope.Close(num/*Undefined()*/);
                      ^
../src/kexec.cc:127:41: error: ‘New’ is not a member of ‘v8::String’
     ThrowException(Exception::TypeError(String::New("kexec: invalid arguments")));
                                         ^
../src/kexec.cc:127:81: error: ‘ThrowException’ was not declared in this scope
     ThrowException(Exception::TypeError(String::New("kexec: invalid arguments")));
                                                                                 ^
../src/kexec.cc:128:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(Undefined());
                  ^
../src/kexec.cc:128:34: error: too few arguments to function ‘v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)’
     return scope.Close(Undefined());
                                  ^
In file included from ../src/kexec.cc:2:0:
/home/yqfang/.node-gyp/0.12.0/deps/v8/include/v8.h:305:28: note: declared here
   friend Handle<Primitive> Undefined(Isolate* isolate);
                            ^
../src/kexec.cc: In function ‘void init(v8::Handle<v8::Object>)’:
../src/kexec.cc:134:47: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [6], v8::Handle<v8::Value> (&)(const int&))’
         NODE_SET_METHOD(target, "kexec", kexec);
                                               ^
../src/kexec.cc:134:47: note: candidate is:
In file included from ../src/kexec.cc:3:0:
/home/yqfang/.node-gyp/0.12.0/src/node.h:228:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/yqfang/.node-gyp/0.12.0/src/node.h:228:13: note:   template argument deduction/substitution failed:
../src/kexec.cc:134:47: note:   cannot convert ‘kexec’ (type ‘v8::Handle<v8::Value>(const int&)’) to type ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’
         NODE_SET_METHOD(target, "kexec", kexec);
                                               ^
kexec.target.mk:85: recipe for target 'Release/obj.target/kexec/src/kexec.o' failed
make: *** [Release/obj.target/kexec/src/kexec.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/spm/node_modules/6to5/node_modules/kexec/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.19.3-031903-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /usr/local/lib/node_modules/spm/node_modules/6to5/node_modules/kexec
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@0.3.5
npm WARN optional dep failed, continuing kexec@1.0.0
```

**Comment by yqfang** [comment]
系统: ubuntu, 内核版本: 3.19.3-031903-generic
cnpm 和npm 都试过了

**Comment by yqfang** [comment]
换用nvm维护nodejs 版本就ok
