### ISSUE TITLE
Ubuntu 下重装系统n 次 装不上 spm 

### ISSUE THREAD

**Issue by yqfang** [spmjs/spm#1248]
系统ubuntu, 用nvm 管理的node 最新: 0.12.2 版本, 不存在sudo 的问题, 所以别让我看#83 了~

先是: 
```
node-gyp configure build
```

报了一堆警告

然后:

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/yqfang/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/node-gy
p/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.19.3-031903-generic
gyp ERR! command "node" "/home/yqfang/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
 "configure" "build"
gyp ERR! cwd /home/yqfang/.nvm/versions/node/v0.12.2/lib/node_modules/spm/node_modules/6to5/node_modules/kexec
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
```

接着自动去下:　phantomjs

下了半个小时，　装好后：　 spm -v 没有反应．．．

**Comment by yqfang** [comment]
@sorrycc  #1247, 有时 sudo 和 非官方 node 版本的问题吧, 用 删掉 原来的 node 后用 nvm 就没有问题, 所以 close 掉了 ~
