### ISSUE TITLE
win7环境下spm2&spm3共存的问题

### ISSUE THREAD

**Issue by ar-insect** [spmjs/spm#1257]
按照共存教程安装配置好后运行spm3出现以下错误信息，请问如何解决？

```bash
module.js:338
    throw err;
          ^
Error: Cannot find module 'colorful'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\wb-jianglm\.spm3\bin\spm3:3:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

**Comment by sorrycc** [comment]
没有执行 `npm install` 安装依赖?

**Comment by ar-insect** [comment]
请问在哪里执行npm install呢？

**Comment by sorrycc** [comment]
`C:\Users\wb-jianglm\.spm3` 这里吧。

**Comment by ar-insect** [comment]
嗯，虽然安装过程中报错了，但是spm3还是安装成功了，thinks~
