### ISSUE TITLE
node 0.12, spm doc 时请求 .map 结尾的文件时报错

### ISSUE THREAD

**Issue by sorrycc** [spmjs/spm#1260]
```
_http_outgoing.js:333
    throw new Error('"name" and "value" are required for setHeader().');
          ^
Error: "name" and "value" are required for setHeader().
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at next (/Users/chencheng/Documents/Work/Libraries/alipay/spm-family/spm/node_modules/nico-spm/lib/server.js:139:11)
    at Server.handler (/Users/chencheng/Documents/Work/Libraries/alipay/spm-family/spm/node_modules/nico-spm/lib/server.js:193:3)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
```

**Comment by nimojs** [comment]
被坑惨了。。。

希望尽快解决，我目前在 spm doc 时都是关闭 map 支持的

**Comment by sorrycc** [comment]
Fixed via nico-spm@0.5.3
