### ISSUE TITLE
spm 3.6 如何build umd 版本的包

### ISSUE THREAD

**Issue by nimojs** [spmjs/spm#1280]
```
now $spm build --umd

          start: build now@0.0.0
         target: http://spmjs.io
          build: compile
/usr/local/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:161
			if(isError) throw e;
			                  ^
TypeError: undefined is not a function
    at Tapable.replacePathVariables (/usr/local/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/lib/TemplatedPathPlugin.js:66:4)
    at Tapable.applyPlugins [as applyPluginsWaterfall] (/usr/local/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/node_modules/tapable/lib/Tapable.js:37:47)
    at replaceKeys (/usr/local/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/lib/UmdMainTemplatePlugin.js:49:24)
    at UmdMainTemplatePlugin.<anonymous> (/usr/local/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/lib/UmdMainTemplatePlugin.js:108:34)
    at Tapable.applyPlugins [as applyPluginsWaterfall] (/usr/local/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/node_modules/tapable/lib/Tapable.js:37:47)
    at Tapable.MainTemplate.render (/usr/local/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/lib/MainTemplate.js:116:17)
    at Tapable.createChunkAssets (/usr/local/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/lib/Compilation.js:783:32)
    at Tapable.<anonymous> (/usr/local/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/lib/Compilation.js:528:8)
    at Tapable.applyPluginsAsync (/usr/local/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Tapable.seal (/usr/local/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/lib/Compilation.js:500:7)
    at Tapable.<anonymous> (/usr/local/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/lib/Compiler.js:394:15)
    at /usr/local/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/node_modules/tapable/lib/Tapable.js:103:11
    at Tapable.<anonymous> (/usr/local/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/lib/Compilation.js:433:10)
    at Tapable.<anonymous> (/usr/local/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/lib/Compilation.js:405:12)
    at /usr/local/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/lib/Compilation.js:321:10
    at Object.async.each (/usr/local/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/node_modules/async/lib/async.js:121:20)
```

**Comment by nimojs** [comment]
我的包是 `paging`
我希望输出的 UMD 使用全局变量 Paging 我该如何配置？

**Comment by nimojs** [comment]
已解决
https://github.com/spmjs/docs/blob/master/project/configuration.md
