### ISSUE TITLE
spm3 doc 命令 在 node 0.12.2 setHeaders 报错

### ISSUE THREAD

**Issue by yize** [spmjs/spm#1281]
环境：

```
node -v
v0.12.1

spm3 -v
3.6.0-rc1
```

报错信息：

```
            200: /static/css/codemirror.css
            200: /src/dialog.css
undefined
_http_outgoing.js:333
    throw new Error('"name" and "value" are required for setHeader().');
    ^
Error: "name" and "value" are required for setHeader().
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at next (/Users/yize/.spm3/node_modules/nico-spm/lib/server.js:141:11)
    at Server.handler (/Users/yize/.spm3/node_modules/nico-spm/lib/server.js:195:3)
    at Server.<anonymous> (/usr/local/lib/node_modules/socket.io/node_modules/engine.io/lib/server.js:369:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/socket.io/lib/index.js:258:16)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)

```

**Comment by pigcan** [comment]
同  https://github.com/spmjs/spm/issues/1260  这个问题我在看

**Comment by nimojs** [comment]
![image](https://cloud.githubusercontent.com/assets/3949015/7388997/a4e0e244-ee9c-11e4-8918-0fc2cd6ce092.png)

可以禁用掉 map 暂时解决这个问题

**Comment by yize** [comment]
@nimojs 嗯，是可以解决问题的。
已经发起 PR ;)
