### ISSUE TITLE
spm ls 报错

### ISSUE THREAD

**Issue by FinalAir** [spmjs/spm#1326]
报错信息：
```
$ spm ls
/usr/local/lib/node_modules/spm/node_modules/father/lib/spm-package.js:118
    throw new Error('no matched version of ' + name);
          ^
Error: no matched version of expect.js
    at resolveDeps (/usr/local/lib/node_modules/spm/node_modules/father/lib/spm-package.js:118:11)
    at /usr/local/lib/node_modules/spm/node_modules/father/lib/spm-package.js:93:18
    at Array.forEach (native)
    at parseDeps (/usr/local/lib/node_modules/spm/node_modules/father/lib/spm-package.js:92:4)
    at SubClass.Package.extend.readPackage (/usr/local/lib/node_modules/spm/node_modules/father/lib/spm-package.js:24:7)
    at SubClass.Class.create._parse (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:93:20)
    at SubClass.Class.create.initialize (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:45:10)
    at new SubClass (/usr/local/lib/node_modules/spm/node_modules/father/node_modules/arale/lib/class.js:53:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/spm/bin/spm-ls:31:11)
    at Module._compile (module.js:460:26)
```
运行环境：
```
mac os Yosemite 10.10.3
$ node -v
v0.12.4
$ spm -v
3.6.0

```

**Comment by afc163** [comment]
重新安装下可以修复吗？

**Comment by FinalAir** [comment]
@afc163 

重新安装过程如下：
```
$ cnpm install spm -g
npm WARN peerDependencies The peer dependency webpack@1.x.x included from istanbul-instrumenter-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency phantomjs@~1.9.1 included from mocha-phantomjs will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated swig@0.14.0: v1.0.0 is a complete rewrite of Swig from the ground up. Previous versions are no longer supported
npm WARN peerDependencies The peer dependency node-libs-browser@>= 0.4.0 <=0.6.0 included from webpack will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
 
> fsevents@0.3.6 install /usr/local/lib/node_modules/spm/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished

> fsevents@0.3.6 install /usr/local/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished

> phantomjs@1.9.17 install /usr/local/lib/node_modules/spm/node_modules/phantomjs
> node install.js

Download already available at /var/folders/7h/wpk9x7z11234k3nx7ql4gf5c0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Extracting zip contents
Removing /usr/local/lib/node_modules/spm/node_modules/phantomjs/lib/phantom
Copying extracted folder /var/folders/7h/wpk9x7z11234k3nx7ql4gf5c0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1433746777838/phantomjs-1.9.8-macosx -> /usr/local/lib/node_modules/spm/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /usr/local/lib/node_modules/spm/node_modules/phantomjs/lib/phantom/bin/phantomjs
/usr/local/bin/spm -> /usr/local/lib/node_modules/spm/bin/spm

> spm@3.6.0 postinstall /usr/local/lib/node_modules/spm
> node scripts/postinstall.js

[spm:preinstall] Phantomjs is installed in /usr/local/lib/node_modules/spm/node_modules/phantomjs/lib/phantomjs.js
spm@3.6.0 /usr/local/lib/node_modules/spm
├── inherits@1.0.0
├── crequire@1.5.4
├── co@3.1.0
├── win-spawn@2.0.0
├── empty-dir@0.1.0
├── spmrc@1.2.0
├── spm-log@0.1.2
├── test-console@0.7.1
├── commander@2.5.1
├── extend@2.0.1
├── archy@1.0.0
├── rimraf@2.2.8
├── colorful@2.1.0
├── scripts-hook@0.1.3 (thunkify@2.1.2, co@4.1.0)
├── debug@2.2.0 (ms@0.7.1)
├── semver@4.1.1
├── fs-extra@0.13.0 (jsonfile@2.0.1, ncp@1.0.1)
├── whoami@0.0.3 (shelljs@0.3.0)
├── internal-ip@1.0.1 (meow@3.1.0)
├── tar@1.0.3 (inherits@2.0.1, block-stream@0.0.8)
├── fstream@1.0.6 (inherits@2.0.1, graceful-fs@3.0.8, mkdirp@0.5.1)
├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.8)
├── fs-symlink@1.1.0 (mz@1.3.0, mkdirp-then@1.0.1, bluebird@2.9.27)
├── exeq@2.0.5 (native-or-bluebird@1.2.0, bluebird@2.9.27)
├── request@2.51.0 (caseless@0.8.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.5.0, tunnel-agent@0.4.0, json-stringify-safe@5.0.1, node-uuid@1.4.3, qs@2.3.3, mime-types@1.0.2, combined-stream@0.0.7, bl@0.9.4, http-signature@0.10.1, form-data@0.2.0, hawk@1.1.1, tough-cookie@1.2.0)
├── vinyl-fs@0.3.13 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.2, vinyl@0.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)
├── father@0.11.0 (extend@1.3.0, arale@0.2.0, debug@1.0.4, vinyl@0.4.6, mixarg@0.2.0, semver@2.3.2, exists-case@0.1.0, css-imports@0.3.1, glob@4.0.6)
├── nico-spm@0.5.3 (commander@2.1.0, markit@0.1.0, underscore@1.5.2, swig@0.14.0, glob@3.2.11, highlight.js@7.5.0)
├── gulp-template@1.1.1 (through2@0.6.5, gulp-util@3.0.5, lodash@2.4.2)
├── spm-client@0.4.1 (co@4.1.0, co-request@0.2.1, minimist@1.1.1, debug@2.1.3, semver@4.2.2, mkdirp@0.5.1, gulp-gunzip@0.0.3, multipipe@0.1.2, gulp-untar2@0.0.6, father@0.10.6)
├── gnode@0.1.1 (regenerator@0.8.29)
├── istanbul@0.3.14 (supports-color@1.3.1, which@1.0.9, abbrev@1.0.7, nopt@3.0.2, wordwrap@0.0.3, once@1.3.2, async@0.9.2, mkdirp@0.5.1, esprima@2.1.0, resolve@1.1.6, fileset@0.1.6, escodegen@1.6.1, handlebars@3.0.0, js-yaml@3.3.1)
├── react-tools@0.12.2 (jstransform@8.2.0, commoner@0.10.1)
├── babel-core@4.7.16 (slash@1.0.0, to-fast-properties@1.0.1, trim-right@1.0.0, path-is-absolute@1.0.0, shebang-regex@1.0.0, fs-readdir-recursive@0.1.2, leven@1.0.2, private@0.1.6, globals@6.4.1, esutils@1.1.6, estraverse@1.9.3, convert-source-map@0.5.1, js-tokens@1.0.0, ast-types@0.7.6, line-numbers@0.2.0, is-integer@1.0.4, commander@2.8.1, repeating@1.1.3, chalk@1.0.0, detect-indent@3.0.1, output-file-sync@1.1.1, acorn-babel@0.11.1-38, source-map-support@0.2.10, source-map@0.4.2, core-js@0.6.1, regexpu@1.1.2, regenerator-babel@0.8.13-2, lodash@3.9.3)
├── inquirer@0.8.5 (figures@1.3.5, ansi-regex@1.1.1, cli-width@1.0.1, through@2.3.7, readline2@0.1.1, chalk@1.0.0, lodash@3.9.3, rx@2.5.3)
├── spm-webpack-server@0.3.4 (combo-url@0.2.0, koa-static@1.4.9, co-request@0.2.1, memory-fs@0.2.0, mime@1.3.4, commander@2.7.1, koa-send@1.3.1, spm-argv@0.1.1, coffee-script@1.9.3, koa@0.19.1, tiny-lr@0.1.5, koa-serve-index@1.0.4, weinre@2.0.0-pre-I0Z7U9OV)
├── node-libs-browser@0.5.2 (https-browserify@0.0.0, tty-browserify@0.0.0, constants-browserify@0.0.1, path-browserify@0.0.0, string_decoder@0.10.31, process@0.11.1, os-browserify@0.1.2, punycode@1.3.2, domain-browser@1.1.4, assert@1.3.0, querystring-es3@0.2.1, timers-browserify@1.4.1, events@1.0.2, stream-browserify@1.0.0, console-browserify@1.1.0, vm-browserify@0.0.4, util@0.10.3, http-browserify@1.7.0, url@0.10.3, readable-stream@1.1.13, buffer@3.2.2, browserify-zlib@0.1.4, crypto-browserify@3.2.8)
├── webpack@1.9.10 (supports-color@1.3.1, interpret@0.5.2, tapable@0.1.9, clone@1.0.2, memory-fs@0.2.0, async@0.9.2, mkdirp@0.5.1, optimist@0.6.1, enhanced-resolve@0.8.6, webpack-core@0.6.5, uglify-js@2.4.23, esprima@1.2.5, watchpack@0.2.8)
├── istanbul-instrumenter-loader@0.1.3
├── spm-webpack@0.3.12 (json-loader@0.5.2, spmtpl-loader@0.1.0, uniq@1.0.1, qs@2.4.2, commander@2.7.1, fs-extra@0.16.5, semver@4.3.6, spm-argv@0.1.1, resolve@1.1.6, glob@5.0.10, rimraf@2.3.4, css-resources@0.1.2, url-loader@0.5.6, file-loader@0.8.4, style-loader@0.8.3, babel-loader@5.0.0, extract-text-webpack-plugin@0.3.8, webpack-core@0.6.5, less-loader@2.1.0, handlebars-loader@0.1.8, handlebars@1.3.0, less@2.4.0, jsx2-loader@0.13.1, autoprefixer-loader@1.2.0, spmcss-loader@0.9.2, babel-core@5.0.13, webpack@1.7.3)
├── phantomjs@1.9.17 (which@1.0.9, progress@1.1.8, kew@0.4.0, request-progress@0.3.1, fs-extra@0.18.4, adm-zip@0.4.4, npmconf@2.1.1, request@2.42.0)
└── mocha-phantomjs@3.5.3 (commander@2.0.0, mocha@1.20.1)
```

然后重新运行spm ls，问题依旧：
```
$ spm ls
/usr/local/lib/node_modules/spm/node_modules/father/lib/spm-package.js:118
    throw new Error('no matched version of ' + name);
          ^
Error: no matched version of expect.js
    at resolveDeps (/usr/local/lib/node_modules/spm/node_modules/father/lib/spm-package.js:118:11)
    at /usr/local/lib/node_modules/spm/node_modules/father/lib/spm-package.js:93:18
    at Array.forEach (native)
    at parseDeps (/usr/local/lib/node_modules/spm/node_modules/father/lib/spm-package.js:92:4)
    at SubClass.Package.extend.readPackage (/usr/local/lib/node_modules/spm/node_modules/father/lib/spm-package.js:24:7)
    at SubClass.Class.create._parse (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:93:20)
    at SubClass.Class.create.initialize (/usr/local/lib/node_modules/spm/node_modules/father/lib/package.js:45:10)
    at new SubClass (/usr/local/lib/node_modules/spm/node_modules/father/node_modules/arale/lib/class.js:53:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/spm/bin/spm-ls:31:11)
    at Module._compile (module.js:460:26)
```

**Comment by afc163** [comment]
你需要先安装依赖到本地，spm ls 显示的是本地包的依赖关系。

```
spm install
```

先。

**Comment by afc163** [comment]
不过这里可以优化下展示，没安装就只显示自己。

**Comment by FinalAir** [comment]
@afc163 
报错是解决了，但是有一个问题，我当前包中是安装过依赖的```spm install seajs --save```.但是没有单独运行```spm install```,这条命令需要单独运行添加依赖感觉上有点奇怪，毕竟我已经运行过```spm init```了。可以考虑优化一下。

**Comment by afc163** [comment]
没有看明白，只要安装过就好。

**Comment by FinalAir** [comment]
@afc163 
我之前就是执行了这三个语句，执行到第三个的时候报错。然后按照你提示的单独执行了一遍```spm install```，问题就解决了。

而spm install帮我添加了对```expect.js```的依赖，同时在```package.json```中添加了
```
"devDependencies": {
      "expect.js": "0.3.1"
    }
```
这个描述，之前json是没有的。
