### ISSUE TITLE
spm 打包es6 语法的 jsx 出错

### ISSUE THREAD

**Issue by wuguanghai45** [spmjs/spm#1363]
要打包的代码
```javascript
import React from 'react'
class Checkbox extends React.Component {
}
export default Checkbox
```
打包jsx文件抛错
```javascript
spm build src/js/components/checkbox.jsx

          start: build src/js/components/checkbox.jsx
         target: http://spmjs.io
          build: start
          error: ./src/js/components/checkbox.jsx
Module build failed: Error: Parse Error: Line 1: Illegal import declaration
    at throwError (~/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/jsx2-loader/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2813:21)
    at throwErrorTolerant (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/jsx2-loader/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2825:24)
    at parseSourceElement (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/jsx2-loader/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6390:17)
    at parseProgramElement (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/jsx2-loader/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6446:16)
    at parseProgramElements (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/jsx2-loader/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6478:29)
    at parseProgram (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/jsx2-loader/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6491:16)
    at Object.parse (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/jsx2-loader/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:7653:23)
    at getAstForSource (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/jsx2-loader/node_modules/react-tools/node_modules/jstransform/src/jstransform.js:251:21)
    at transform (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/jsx2-loader/node_modules/react-tools/node_modules/jstransform/src/jstransform.js:274:11)
    at innerTransform (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/jsx2-loader/node_modules/react-tools/main.js:94:10)
    at Object.module.exports.transformWithDetails (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/jsx2-loader/node_modules/react-tools/main.js:34:18)
    at Object.module.exports (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/jsx2-loader/index.js:19:30)
 @ multi src/js/components/checkbox
```

打包js文件无异常
```javascript
spm build src/js/components/checkbox.js                  
          start: build src/js/components/checkbox.js
         target: http://spmjs.io
          build: start
      generated: src/js/components/checkbox.js 153.96kB
          build: done
         finish: build src/js/components/checkbox.js (6168ms)
```

package spm 配置
```json
  "spm": {
    "main": "./src/js/index.js",
    "build": {
      "jsx": {},
      "babel": {}
    },
    "dependencies": {
      "react": "^0.13.3"
    }
  },
```

**Comment by sorrycc** [comment]
试下这个配置呢。

```javascript
{
  "spm": {
    "build": {
      "babel": true,
      "loader": {
        ".jsx": "babel"
      }
    }
  }
}
```

**Comment by wuguanghai45** [comment]
试了下
```json
  {
  "spm": {
    "main": "./src/js/index.js",
    "build": {
      "babel": true,
      "loader": {
        ".jsx": "babel"
      }
    },
    "dependencies": {
      "react": "^0.13.3"
    }
  }
}
```
我一开始列举的代码可以正常打包但是把代码补全后
```javascript
"use strict"

require('../../less/checkbox.less')
import React from 'react'
import classnames from 'classnames'

class Checkbox extends React.Component {
  static displayName = "Checkbox"

  static propTypes = {
    checked: React.PropTypes.bool,
    children: React.PropTypes.any,
    className: React.PropTypes.string,
    index: React.PropTypes.number,
    onChange: React.PropTypes.func,
    readOnly: React.PropTypes.bool,
    style: React.PropTypes.object,
    text: React.PropTypes.any,
    value: React.PropTypes.any
  }

  componentWillReceiveProps (nextProps) {
    if (nextProps.checked !== this.props.checked) {
      this.setState({ checked: nextProps.checked })
    }
  }

  state = {
    checked: !!this.props.checked
  }

  handleChange (event) {
    if (this.props.readOnly) {
      return
    }

    this.setState({ checked: event.target.checked })
    if (this.props.onChange) {
      this.props.onChange(event.target.checked, this.props.value, this.props.index)
    }
  }

  getValue () {
    return React.findDOMNode(this.refs.input).checked ? (this.props.value || true) : false
  }

  setValue (value) {
    var checked = value === true || value === 1 || value === this.state.value
    this.setState({ checked: checked })
  }

  render () {
    return (
      <label style={this.props.style} className={ classnames(this.props.className, "checkbox") }>
        <input ref="input"
          type="checkbox"
          disabled={this.props.readOnly}
          onChange={this.handleChange.bind(this)}
          checked={this.state.checked}
          value={this.props.value}
        />
        {this.props.text}
        {this.props.children}
      </label>
    )
  }
}

require('./formControl.jsx').register(

  'checkbox',

  function (props) {
    return <Checkbox {...props} />
  },

  Checkbox
)

export default Checkbox
```
编译出错
```javascript
Module build failed: SyntaxError: $CWD/src/js/components/checkbox.jsx: Unexpected token (8:21)
   6 | 
   7 | class Checkbox extends React.Component {
>  8 |   static displayName = "Checkbox"
     |                      ^
   9 | 
  10 |   static propTypes = {
  11 |     checked: React.PropTypes.bool,
    at Parser.pp.raise (~/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/babel-core/lib/acorn/src/location.js:73:13)
    at Parser.pp.unexpected (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/babel-core/lib/acorn/src/parseutil.js:87:8)
    at Parser.pp.parseClassProperty (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/babel-core/lib/acorn/src/statement.js:546:61)
    at Parser.parseClassProperty (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/babel-core/lib/acorn/plugins/flow.js:724:20)
    at Parser.pp.parseClass (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/babel-core/lib/acorn/src/statement.js:508:32)
    at Parser.pp.parseStatement (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/babel-core/lib/acorn/src/statement.js:72:19)
    at Parser.parseStatement (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/babel-core/lib/acorn/plugins/flow.js:636:22)
    at Parser.pp.parseTopLevel (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/babel-core/lib/acorn/src/statement.js:22:21)
    at Object.parse (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/babel-core/lib/acorn/src/index.js:106:12)
    at exports.default (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/babel-core/lib/babel/helpers/parse.js:47:19)
    at File.parse (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/babel-core/lib/babel/transformation/file/index.js:533:46)
    at File.addCode (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/babel-core/lib/babel/transformation/file/index.js:615:24)
    at /home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:89:12
    at File.wrap (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/babel-core/lib/babel/transformation/file/index.js:579:7)
    at TransformerPipeline.transform (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:88:17)
    at transpile (/home/wgh/.nvm/versions/node/v0.12.0/lib/node_modules/spm/node_modules/spm-webpack/node_modules/babel-loader/index.js:12:22)
 @ multi src/js/components/checkbox

```
顺便说一下场景，我是为了搬运git 代码到spm 上面，原作者是用webpack打包的
 [react-ui](https://github.com/Lobos/react-ui)

**Comment by sorrycc** [comment]
同步了一份这个包过来，看下能不能用。http://spmjs.io/package/rctui

**Comment by wuguanghai45** [comment]
装了一下然后项目里面引用了一下, spm 抛错
```javascript
ERROR in ./spm_modules/rctui/0.3.2/src/js/index.js
Module parse failed: /home/wuguanghai/rails/wzhw_erp/public/static/spm_modules/rctui/0.3.2/src/js/index.js Line 3: Unexpected reserved word
You may need an appropriate loader to handle this file type.
| "use strict"
| 
| export const Checkbox = require('./components/checkbox.jsx')
| export const CheckboxGroup = require('./components/checkboxGroup.jsx')
| export const Datetime = require('./components/datetime.jsx')
 @ ./app/components/Products/Index.js 13:13-29
```

**Comment by wuguanghai45** [comment]
重新定位了一下错误　

```javascript
  static displayName = "Checkbox"
```
是因为这句代码无法编译的问题
ES6 我也不熟悉，　现在感觉和jsx没有关系

**Comment by afc163** [comment]
感觉是用了 es7 的特性。https://gist.github.com/jeffmo/054df782c05639da2adb

**Comment by wuguanghai45** [comment]
@afc163  那现在spm 会不会支持es7

**Comment by wuguanghai45** [comment]
最近研究了一下spm-webpack 源码 和 babel 配置,  发现spm babel 兼容 es7 语法
http://babeljs.io/docs/advanced/transformers/#optional
配置如下

```json
"spm": {
  "build": {
    "babel": {
      "optional": [
        "es7.classProperties"
      ]
    }
  },
}

**Comment by honger05** [comment]
赞！   刚好碰到这个问题
