### ISSUE TITLE
gnode 不支持 Promise的问题什么时候能解决？

### ISSUE THREAD

**Issue by liveme** [spmjs/spm#1366]
目前在3.6.10发现spm doc无法使用，之前也有童鞋提过issues： https://github.com/spmjs/spm/issues/1192

请问何时能解决？

````javascript
$ spm doc

           deps: javascript
       generate: _site/_bundle.js

/usr/local/lib/node_modules/spm/node_modules/co/index.js:50
  return new Promise(function(resolve, reject) {
             ^
ReferenceError: Promise is not defined
    at co (/usr/local/lib/node_modules/spm/node_modules/co/index.js:50:14)
    at createPromise (/usr/local/lib/node_modules/spm/node_modules/co/index.js:30:15)
    at /usr/local/lib/node_modules/spm/lib/doc.js:111:5
    at getWebpackOpts (/usr/local/lib/node_modules/spm/node_modules/spm-webpack/lib/build.js:260:24)
    at webpackWrap (/usr/local/lib/node_modules/spm/lib/doc.js:68:3)
    at server (/usr/local/lib/node_modules/spm/lib/doc.js:48:3)
    at module.exports (/usr/local/lib/node_modules/spm/lib/doc.js:30:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/spm/bin/spm-doc:52:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
````

**Comment by liveme** [comment]
安装升级node后解决
