### ISSUE TITLE
关于spm3 install使用的问题

### ISSUE THREAD

**Issue by petsa** [spmjs/spm#1370]
刚安装完spm3，随便安装一个arale组件，提示报错：

/usr/local/lib/node_modules/spm/node_modules/inquirer/node_modules/rx/dist/rx.js:579
    throw e;
          ^
ReferenceError: Promise is not defined
    at co (/usr/local/lib/node_modules/spm/node_modules/co/index.js:50:14)
    at createPromise (/usr/local/lib/node_modules/spm/node_modules/co/index.js:30:15)
    at PromptUI.completed (/usr/local/lib/node_modules/spm/bin/spm-login:49:3)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/spm/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/spm/node_modules/inquirer/node_modules/rx/dist/rx.js:1793:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/spm/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AnonymousObserver.tryCatcher (/usr/local/lib/node_modules/spm/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/spm/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.%

**Comment by petsa** [comment]
报错是和brew安装的nodejs目录问题有关吗

**Comment by sorrycc** [comment]
换 nvm 安装 node，然后 node 版本换成 0.12 试试。我估计是可选依赖包安装出错了导致的。

**Comment by haidao2620** [comment]
我出现了这种报错，愁死了，这是spm本身的bug还是node方面的问题？

**Comment by WG-C** [comment]
+1

**Comment by techbirds** [comment]
+1

**Comment by feichao** [comment]
node版本太低，去安装最新的node即可

**Comment by pigcan** [comment]
node 版本 需要大于  `0.12.0`
