### ISSUE TITLE
打包less 文件如果没定义@变量直接抛错, 有些人统一把变量放到一个文件里面

### ISSUE THREAD

**Issue by wuguanghai45** [spmjs/spm#1374]
有多个文件 flow.less  gantt.less  mermaid.less  sequenceDiagram.less  variables.less
其中variables 是用来专门存储变量的
其他文件没有定义@变量
打包的时候抛错

```javascript
Module build failed: variable @blue is undefined
 @ $CWD/index.less (line 7, column 9)
 near lines:
   h1 {
     color: @blue;
   }
Error: variable @blue is undefined
 @ /home/wuguanghai/spm/examples/less/index.less (line 7, column 9)
 near lines:
   h1 {
     color: @blue;
   }
    at formatLessRenderError (/home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/node_modules/less-loader/index.js:167:12)
    at /home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/node_modules/less-loader/index.js:62:19
    at /home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/node_modules/less/lib/less/render.js:33:38
    at /home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/node_modules/less/lib/less/parse.js:63:17
    at Object.finish [as _finish] (/home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/node_modules/less/lib/less/parser/parser.js:183:28)
    at Object.ImportVisitor._onSequencerEmpty (/home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/node_modules/less/lib/less/visitors/import-visitor.js:35:14)
    at ImportSequencer.tryRun (/home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/node_modules/less/lib/less/visitors/import-sequencer.js:50:14)
    at Object.ImportVisitor.run (/home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/node_modules/less/lib/less/visitors/import-visitor.js:29:25)
    at Object.Parser.parse (/home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/node_modules/less/lib/less/parser/parser.js:189:22)
    at Object.parse (/home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/node_modules/less/lib/less/parse.js:61:18)
    at Object.render (/home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/node_modules/less/lib/less/render.js:25:18)
    at Object.module.exports (/home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/node_modules/less-loader/index.js:55:7)

```

**Comment by sorrycc** [comment]
直接用 lessc 编译会报错吗?

**Comment by wuguanghai45** [comment]
刚试了下build 一个文件
```javascript
@import "variables";
@import "flow";
@import "sequenceDiagram";
@import "gantt";
@import "variables";

text {
  font-family: 'trebuchet ms', verdana, arial;
  font-size:14px;
}
```
没有问题成功通过
应该是只是单独require 一个没有定义变量的less 文件造成的
