### ISSUE TITLE
spm publish 路径出错

### ISSUE THREAD

**Issue by wuguanghai45** [spmjs/spm#1378]
搬运完成后 publish 路径出错
spm_modules/marked/0.3.5/marked

然后初始化了一个spm 包 用作测试上传
spm_modules/wgh-test/0.0.0/b/
路径多了个b b是我项目文件夹名 不是项目名称

**Comment by wuguanghai45** [comment]
然后导致引用包出错
```js
  start: build react-markdown-to-html@1.0.11
         target: http://spmjs.io
      installed: jquery@2.1.4, lodash@3.7.0, marked@0.3.5
          build: start
/home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:163
			if(isError) throw e;
			                  ^
Error: ENOENT, no such file or directory '/home/wuguanghai/node_modules/react-markdown-to-html/spm_modules/marked/0.3.5/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at fs.readFileSync (fs.js:352:15)
    at getPkg (/home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/lib/SPMModuleParser.js:16:21)
    at getPkgVersion (/home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/lib/SPMModuleParser.js:122:15)
    at Array.map (native)
    at getVersion (/home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/lib/SPMModuleParser.js:107:6)
    at new SPMModuleParser (/home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/lib/SPMModuleParser.js:80:20)
    at Tapable.<anonymous> (/home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/lib/SPMWebpackPlugin.js:15:12)
    at Tapable.applyPluginsParallelBailResult (/home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/node_modules/tapable/lib/Tapable.js:139:14)
    at Tapable.doResolve (/home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:83:15)
    at Tapable.resolve (/home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:43:33)
    at Tapable.resolve (/home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:23:14)
    at Tapable.<anonymous> (/home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/lib/NormalModuleFactory.js:80:28)
    at /home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/node_modules/async/lib/async.js:689:13
    at /home/wuguanghai/.nvm/versions/v0.12.7/lib/node_modules/spm/node_modules/spm-webpack/node_modules/webpack/node_modules/async/lib/async.js:239:13
```

**Comment by wuguanghai45** [comment]
spm 版本 3.6.11 
今天刚升级了下

**Comment by wuguanghai45** [comment]
spm 版本 3.6.11

**Comment by wuguanghai45** [comment]
好像是我运行spm publish 打包的时候把上级的文件夹也打包了...

**Comment by wuguanghai45** [comment]
好像我系统的问题, 不麻烦你们了

**Comment by wuguanghai45** [comment]
解决不了..求助...
不知道是 js 问题还是

**Comment by wuguanghai45** [comment]
有可能是系统版本问题, spm 重装多次 , node 也重装多次

Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid

**Comment by wuguanghai45** [comment]
最后追踪到node tar lib/pack.js　文件
把　wprops.path = path.relative(root, entry.path || '')
改成 wprops.path = path.relative(entry.root.path, entry.path || '')　临时性解决问题．．

**Comment by alvin2ye** [comment]
:+1:

**Comment by wuguanghai45** [comment]
最新版 nodejs 4.1.1 没有问题.  
怀疑时node 版本引发的问题
